enum ActionInfractionEnum {
  ECRIRE_EMAIL = 'ECRIRE_EMAIL',
  ECRIRE_COURRIER_MISE_EN_DEMEURE = 'ECRIRE_COURRIER_MISE_EN_DEMEURE',
  INDIQUER_PROBABLEMENT_RESOLU = 'INDIQUER_PROBABLEMENT_RESOLU',
  FERMER_INFRACTION = 'FERMER_INFRACTION',
  ECRIRE_COURRIER_CONSTAT_CARENCE = 'ECRIRE_COURRIER_CONSTAT_CARENCE',
  ECRIRE_COURRIER_COMPLEMENTAIRE = 'ECRIRE_COURRIER_COMPLEMENTAIRE',
  REOUVRIR_INFRACTION = 'REOUVRIR_INFRACTION',
}
export default ActionInfractionEnum;
