enum ActionInfractionEnum {
  ECRIRE_EMAIL = 'ECRIRE_EMAIL',
  AJOUTER_COMMENTAIRE = 'AJOUTER_COMMENTAIRE',
  UPLOAD_FILES = 'UPLOAD_FILES',
  ECRIRE_COURRIER_MISE_EN_DEMEURE = 'ECRIRE_COURRIER_MISE_EN_DEMEURE',
  ECRIRE_COURRIER_CONSTAT_CARENCE = 'ECRIRE_COURRIER_CONSTAT_CARENCE',
  ECRIRE_COURRIER_COMPLEMENTAIRE = 'ECRIRE_COURRIER_COMPLEMENTAIRE',
  CHANGER_STATUT = 'CHANGER_STATUT',
  MODIFIER_DATE_BUTOIR = 'MODIFIER_DATE_BUTOIR',
}
export default ActionInfractionEnum;
